function accountsScreen() {
  return mainShell({title:'Aktivní účty',active:'settings',classes:'content--tight',content:'<button class="button button--wide" data-action="add-technician">'+svg('addPerson')+'Přidat technika</button><article class="outlined-card list-row">'+svg('badge')+'<div class="flex-1"><h3>'+demo.technician.name+'</h3><p class="supporting">Aktivní účet</p></div><button class="icon-button" data-action="edit-technician" aria-label="Upravit technika">'+svg('penOutline')+'</button><button class="icon-button text-danger" data-action="native-only" aria-label="Odstranit technika">'+svg('trashOutline')+'</button></article>'});
}
function buildingsScreen() {
  return mainShell({title:'Domy',active:'settings',classes:'content--tight',content:'<button class="button button--wide" data-action="building-editor">'+svg('addTask')+'Přidat dům</button>'+demo.buildings.map(b=>'<article class="outlined-card list-row">'+svg('buildingOutline')+'<div class="flex-1"><h3>'+b.address+'</h3><p class="supporting">Interval 30 dní</p></div><button class="icon-button" data-action="building-editor" data-key="'+b.id+'" aria-label="Upravit dům">'+svg('penOutline')+'</button><button class="icon-button text-danger" data-action="native-only" aria-label="Odstranit dům">'+svg('trashOutline')+'</button></article>').join('')});
}
function backupScreen() {
  return mainShell({title:'Export a import',active:'settings',content:'<div><h2 style="font-size:22px;line-height:28px">Export a import dat</h2><p>Šifrovaný soubor obsahuje účty, databázi, originály i publikované fotografie, PDF a nastavení. Žádná data se neposílají do cloudu.</p></div>'+demoPassword('backup-password','Heslo zálohy (min. 8 znaků)')+demoPassword('backup-repeat','Heslo znovu pro export')+'<button class="button" data-action="native-only">'+svg('uploadOutline')+'Exportovat data</button><section class="info-card"><h3>Bezpečnost před aktualizací</h3><p>Vytvoří a ověří úplnou lokální zálohu a uloží kontrolní otisk dat. Po instalaci novější verze DSO automaticky potvrdí, zda data zůstala zachována.</p><button class="button" data-action="native-only">Připravit bezpečný update</button></section><button class="button button--outlined" data-action="native-only">'+svg('downloadOutline')+'Importovat a sloučit data</button><hr class="divider"/><h3>Poslední zálohy</h3>'});
}
function integrityScreen() {
  return mainShell({title:'Kontrola dat',active:'settings',content:'<div><h2 style="font-size:22px;line-height:28px">Kontrola integrity</h2><p>Ověří SQLite, existenci a SHA‑256 originálů i PDF a upozorní na nedostatek místa.</p></div><button class="button button--wide" data-action="native-only">'+svg('checklistOutline')+'Spustit kontrolu</button>'});
}
function deviceScreen() {
  return mainShell({title:'Telefon',active:'settings',content:'<div><h2 style="font-size:22px;line-height:28px">Telefon a instalační profil</h2><p>Kontrola telefonu je lokální. Internet může využít pouze spuštěná hlasová poznámka.</p></div><section class="outlined-card card-pad stack"><h3>Diagnostika není dostupná</h3><button class="button" style="align-self:flex-start" data-action="native-only">'+svg('history')+'Spustit znovu</button></section><section class="outlined-card card-pad stack"><h3>Stav instalace</h3><p>✓ Přihlášení technika</p><p>✓ Technik</p><p>○ Fotoaparát</p><p>○ Lokální záloha</p></section>'});
}
function printScreen() {
  return mainShell({title:'Tisk',active:'settings',content:'<h2 style="font-size:22px;line-height:28px">Nativní tisk Android</h2><section class="outlined-card card-pad stack">'+svg('printOutline')+'<p>Digitální Správa Objektů používá systémový tisk Androidu. Tiskárnu připojte v telefonu; aplikace pak nabídne stejné tiskárny jako ostatní aplikace.</p><p class="small">Protokol se otevře na A4 na šířku, fotodokumentace na A4 na výšku a kompletní PDF zachová orientaci jednotlivých stran.</p><button class="button button--wide" data-action="android-settings">Otevřít systémové nastavení tisku</button></section>'});
}
